queue_rules:
  - name: default
    merge_conditions: []

pull_request_rules:
  - name: auto-merge on one approval
    conditions:
      - "#approved-reviews-by >= 1"
      - "-draft"
    actions:
      merge:
        method: squash
